vich_uploader:
    db_driver: orm

    mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        profile_pictures:
            uri_prefix: /images/profile_pictures
            upload_destination: '%kernel.project_dir%/public/images/profile_pictures'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true